$ANSIBLE_VAULT;1.1;AES256
63383763346631623735333664306438396339343361333237373934353135323866376465373430
3632333065643466393738353164373432643865636162390a346661623430386233353530633235
62303766386230636138643437656137383735333832393066616665353235363234353265373765
3230316433396262650a643536356661366462623961616631366235306435363739363938356537
31333234353764306662393831643334653938633631633438306335656533653133393462663439
37663731613734366130656130383231333562616330653831343939346134616436323130376364
38316132613333653832643337313737393437333631633362653839306634313635356464363533
65333736326338653061623833623837663761393335326430623135336636663666323535313065
3932
